# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/laboratorio/Desktop/Somador de 2 bits/Somador de 2 bits.cache/wt} [current_project]
set_property parent.project_path {C:/Users/laboratorio/Desktop/Somador de 2 bits/Somador de 2 bits.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/laboratorio/Desktop/Somador de 2 bits/Somador de 2 bits.srcs/sources_1/new/somador_2bits.vhdl}}
synth_design -top somador_2bits -part xc7k70tfbv676-1
write_checkpoint -noxdef somador_2bits.dcp
catch { report_utilization -file somador_2bits_utilization_synth.rpt -pb somador_2bits_utilization_synth.pb }
