# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/laboratorio/Desktop/DetectorDeSequencia/DetectorDeSequencia.cache/wt [current_project]
set_property parent.project_path C:/Users/laboratorio/Desktop/DetectorDeSequencia/DetectorDeSequencia.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/laboratorio/Desktop/DetectorDeSequencia/DetectorDeSequencia.srcs/sources_1/new/DetectorSequencia.vhd
synth_design -top detector_11010 -part xc7k70tfbv676-1
write_checkpoint -noxdef detector_11010.dcp
catch { report_utilization -file detector_11010_utilization_synth.rpt -pb detector_11010_utilization_synth.pb }
