# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/laboratorio/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/laboratorio/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/laboratorio/Desktop/project_1/project_1.srcs/sources_1/new/Semaforo.vhd
synth_design -top semaforo_com_btn -part xc7k70tfbv676-1
write_checkpoint -noxdef semaforo_com_btn.dcp
catch { report_utilization -file semaforo_com_btn_utilization_synth.rpt -pb semaforo_com_btn_utilization_synth.pb }
